# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'precalculateForm.ui'
#
# Created: Sun Apr 24 23:11:29 2016
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_precalculate(object):
    def setupUi(self, precalculate):
        precalculate.setObjectName("precalculate")
        precalculate.resize(309, 246)
        self.label1 = QtWidgets.QLabel(precalculate)
        self.label1.setGeometry(QtCore.QRect(10, 10, 321, 16))
        self.label1.setObjectName("label1")
        self.calculateButton = QtWidgets.QPushButton(precalculate)
        self.calculateButton.setGeometry(QtCore.QRect(200, 200, 81, 24))
        self.calculateButton.setObjectName("calculateButton")
        self.deleteButton = QtWidgets.QPushButton(precalculate)
        self.deleteButton.setGeometry(QtCore.QRect(180, 10, 111, 24))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.deleteButton.setFont(font)
        self.deleteButton.setToolTip("")
        self.deleteButton.setCheckable(False)
        self.deleteButton.setChecked(False)
        self.deleteButton.setObjectName("deleteButton")
        self.cancelButton = QtWidgets.QPushButton(precalculate)
        self.cancelButton.setGeometry(QtCore.QRect(20, 200, 83, 24))
        self.cancelButton.setObjectName("cancelButton")
        self.Jmax = QtWidgets.QLineEdit(precalculate)
        self.Jmax.setGeometry(QtCore.QRect(180, 70, 91, 20))
        self.Jmax.setMaxLength(5)
        self.Jmax.setFrame(True)
        self.Jmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Jmax.setObjectName("Jmax")
        self.label = QtWidgets.QLabel(precalculate)
        self.label.setGeometry(QtCore.QRect(60, 70, 57, 20))
        self.label.setStatusTip("")
        self.label.setObjectName("label")
        self.availableLabel = QtWidgets.QLabel(precalculate)
        self.availableLabel.setGeometry(QtCore.QRect(10, 40, 321, 16))
        self.availableLabel.setObjectName("availableLabel")
        self.Kmax = QtWidgets.QLineEdit(precalculate)
        self.Kmax.setGeometry(QtCore.QRect(180, 100, 91, 20))
        self.Kmax.setMaxLength(5)
        self.Kmax.setFrame(True)
        self.Kmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Kmax.setObjectName("Kmax")
        self.label_2 = QtWidgets.QLabel(precalculate)
        self.label_2.setGeometry(QtCore.QRect(60, 100, 57, 20))
        self.label_2.setStatusTip("")
        self.label_2.setObjectName("label_2")
        self.Mmax = QtWidgets.QLineEdit(precalculate)
        self.Mmax.setGeometry(QtCore.QRect(180, 130, 91, 20))
        self.Mmax.setMaxLength(5)
        self.Mmax.setFrame(True)
        self.Mmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Mmax.setObjectName("Mmax")
        self.label_3 = QtWidgets.QLabel(precalculate)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 57, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(precalculate)
        self.label_4.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label_4.setObjectName("label_4")
        self.sizeLabel = QtWidgets.QLabel(precalculate)
        self.sizeLabel.setGeometry(QtCore.QRect(140, 160, 131, 20))
        self.sizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sizeLabel.setObjectName("sizeLabel")
        self.label_6 = QtWidgets.QLabel(precalculate)
        self.label_6.setGeometry(QtCore.QRect(280, 160, 31, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(precalculate)
        QtCore.QMetaObject.connectSlotsByName(precalculate)

    def retranslateUi(self, precalculate):
        _translate = QtCore.QCoreApplication.translate
        precalculate.setWindowTitle(_translate("precalculate", "Precalculate 2D matrix elements"))
        self.label1.setText(_translate("precalculate", "Currently available:"))
        self.calculateButton.setText(_translate("precalculate", "Calculate"))
        self.deleteButton.setText(_translate("precalculate", "Delete cache"))
        self.cancelButton.setText(_translate("precalculate", "Cancel"))
        self.Jmax.setToolTip(_translate("precalculate", "<html><head/><body><p>Maximum J quantum number you will need. Depends on the molecule and the laser pulse(es).</p></body></html>"))
        self.Jmax.setPlaceholderText(_translate("precalculate", "0"))
        self.label.setToolTip(_translate("precalculate", "<html><head/><body><p>Maximum J quantum number you will need. Depends on the molecule and the laser pulse(es).</p></body></html>"))
        self.label.setText(_translate("precalculate", "Jmax:"))
        self.availableLabel.setText(_translate("precalculate", "Jmax = 230, Kmax = 5, Mmax = 50"))
        self.Kmax.setToolTip(_translate("precalculate", "<html><head/><body><p>Maximum K quantum number you will need. Depends on the molecule and the initial temperature. Linear molecules always have K=0.</p></body></html>"))
        self.Kmax.setPlaceholderText(_translate("precalculate", "0"))
        self.label_2.setToolTip(_translate("precalculate", "<html><head/><body><p>Maximum K quantum number you will need. Depends on the molecule and the initial temperature. Linear molecules always have K=0.</p></body></html>"))
        self.label_2.setText(_translate("precalculate", "Kmax:"))
        self.Mmax.setToolTip(_translate("precalculate", "Maximum K quantum number you will need. Depends on the molecule and the initial temperature."))
        self.Mmax.setPlaceholderText(_translate("precalculate", "0"))
        self.label_3.setToolTip(_translate("precalculate", "Maximum M quantum number you will need. Depends on the molecule and the initial temperature."))
        self.label_3.setText(_translate("precalculate", "Mmax:"))
        self.label_4.setText(_translate("precalculate", "Required size:"))
        self.sizeLabel.setText(_translate("precalculate", "0"))
        self.label_6.setText(_translate("precalculate", "MB"))

