[project]
name = "alignment-calculator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "matplotlib>=3.7.5",
    "numpy>=1.24.4",
    "pyqt5==5.15.2",
    "scipy>=1.10.1",
]
